server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css)$ {
        expires 1h;
        try_files $uri =404;
    }

    location ~* \.(png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf)$ {
        expires 7d;
        try_files $uri =404;
    }
}